name: "Bug report 🐛"
description: Create a report to help us improve
labels: ["C-bug"]
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: List the version(s) of `hyper`, and any relevant hyper dependency (such as `h2` if this is related to HTTP/2).
      placeholder: "hyper 1.0.0, h2 0.4.0"
    validations:
      required: true

  - type: input
    id: platform
    attributes:
      label: Platform
      description: The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)
      placeholder: "Linux 5.15.0 x86_64 / Windows 11 64-bit"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A short summary of the bug
      placeholder: "Brief description of what went wrong"
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Code sample that causes the bug (if applicable)
      render: rust
      placeholder: |
        use hyper::...;

        fn main() {
            // code that reproduces the bug
        }

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (stack traces, related issues, etc.)
