use unicase::UniCase;

header! {
    #[doc="`Access-Control-Request-Headers` header, part of"]
    #[doc="[CORS](http://www.w3.org/TR/cors/#access-control-request-headers-request-header)"]
    #[doc=""]
    #[doc="The `Access-Control-Request-Headers` header indicates which headers will"]
    #[doc="be used in the actual request as part of the preflight request."]
    #[doc="during the actual request."]
    #[doc=""]
    #[doc="# ABNF"]
    #[doc="```plain"]
    #[doc="Access-Control-Allow-Headers: \"Access-Control-Allow-Headers\" \":\" #field-name"]
    #[doc="```"]
    #[doc=""]
    #[doc="# Example values"]
    #[doc="* `accept-language, date`"]
    #[doc=""]
    #[doc="# Examples"]
    #[doc="```"]
    #[doc="# extern crate hyper;"]
    #[doc="# extern crate unicase;"]
    #[doc="# fn main() {"]
    #[doc="// extern crate unicase;"]
    #[doc=""]
    #[doc="use hyper::header::{Headers, AccessControlRequestHeaders};"]
    #[doc="use unicase::UniCase;"]
    #[doc=""]
    #[doc="let mut headers = Headers::new();"]
    #[doc="headers.set("]
    #[doc="    AccessControlRequestHeaders(vec![UniCase(\"date\".to_owned())])"]
    #[doc=");"]
    #[doc="# }"]
    #[doc="```"]
    #[doc="```"]
    #[doc="# extern crate hyper;"]
    #[doc="# extern crate unicase;"]
    #[doc="# fn main() {"]
    #[doc="// extern crate unicase;"]
    #[doc=""]
    #[doc="use hyper::header::{Headers, AccessControlRequestHeaders};"]
    #[doc="use unicase::UniCase;"]
    #[doc=""]
    #[doc="let mut headers = Headers::new();"]
    #[doc="headers.set("]
    #[doc="    AccessControlRequestHeaders(vec!["]
    #[doc="        UniCase(\"accept-language\".to_owned()),"]
    #[doc="        UniCase(\"date\".to_owned()),"]
    #[doc="    ])"]
    #[doc=");"]
    #[doc="# }"]
    #[doc="```"]
    (AccessControlRequestHeaders, "Access-Control-Request-Headers") => (UniCase<String>)*

    test_access_control_request_headers {
        test_header!(test1, vec![b"accept-language, date"]);
    }
}
