use unicase::UniCase;

header! {
    #[doc="`Access-Control-Allow-Headers` header, part of"]
    #[doc="[CORS](http://www.w3.org/TR/cors/#access-control-allow-headers-response-header)"]
    #[doc=""]
    #[doc="The `Access-Control-Allow-Headers` header indicates, as part of the"]
    #[doc="response to a preflight request, which header field names can be used"]
    #[doc="during the actual request."]
    #[doc=""]
    #[doc="# ABNF"]
    #[doc="```plain"]
    #[doc="Access-Control-Allow-Headers: \"Access-Control-Allow-Headers\" \":\" #field-name"]
    #[doc="```"]
    #[doc=""]
    #[doc="# Example values"]
    #[doc="* `accept-language, date`"]
    #[doc=""]
    #[doc="# Examples"]
    #[doc="```"]
    #[doc="# extern crate hyper;"]
    #[doc="# extern crate unicase;"]
    #[doc="# fn main() {"]
    #[doc="// extern crate unicase;"]
    #[doc=""]
    #[doc="use hyper::header::{Headers, AccessControlAllowHeaders};"]
    #[doc="use unicase::UniCase;"]
    #[doc=""]
    #[doc="let mut headers = Headers::new();"]
    #[doc="headers.set("]
    #[doc="    AccessControlAllowHeaders(vec![UniCase(\"date\".to_owned())])"]
    #[doc=");"]
    #[doc="# }"]
    #[doc="```"]
    #[doc="```"]
    #[doc="# extern crate hyper;"]
    #[doc="# extern crate unicase;"]
    #[doc="# fn main() {"]
    #[doc="// extern crate unicase;"]
    #[doc=""]
    #[doc="use hyper::header::{Headers, AccessControlAllowHeaders};"]
    #[doc="use unicase::UniCase;"]
    #[doc=""]
    #[doc="let mut headers = Headers::new();"]
    #[doc="headers.set("]
    #[doc="    AccessControlAllowHeaders(vec!["]
    #[doc="        UniCase(\"accept-language\".to_owned()),"]
    #[doc="        UniCase(\"date\".to_owned()),"]
    #[doc="    ])"]
    #[doc=");"]
    #[doc="# }"]
    #[doc="```"]
    (AccessControlAllowHeaders, "Access-Control-Allow-Headers") => (UniCase<String>)*

    test_access_control_allow_headers {
        test_header!(test1, vec![b"accept-language, date"]);
    }
}
