use header::{Language, QualityItem};

header! {
    #[doc="`Content-Language` header, defined in"]
    #[doc="[RFC7231](https://tools.ietf.org/html/rfc7231#section-3.1.3.2)"]
    #[doc=""]
    #[doc="The `Content-Language` header field describes the natural language(s)"]
    #[doc="of the intended audience for the representation.  Note that this"]
    #[doc="might not be equivalent to all the languages used within the"]
    #[doc="representation."]
    #[doc=""]
    #[doc="# ABNF"]
    #[doc="```plain"]
    #[doc="Content-Language = 1#language-tag"]
    #[doc="```"]
    #[doc=""]
    #[doc="# Example values"]
    #[doc="* `da`"]
    #[doc="* `mi, en`"]
    #[doc=""]
    #[doc="# Examples"]
    #[doc="```"]
    #[doc="use hyper::header::{Headers, ContentLanguage, Language, qitem};"]
    #[doc=""]
    #[doc="let mut headers = Headers::new();"]
    #[doc="headers.set("]
    #[doc="    ContentLanguage(vec!["]
    #[doc="        qitem("]
    #[doc="            Language { "]
    #[doc="                 primary: \"en\".to_owned(),"]
    #[doc="                 sub: None,"]
    #[doc="            }"]
    #[doc="        ),"]
    #[doc="    ])"]
    #[doc=");"]
    #[doc="```"]
    #[doc="```"]
    #[doc="use hyper::header::{Headers, ContentLanguage, Language, qitem};"]
    #[doc=""]
    #[doc="let mut headers = Headers::new();"]
    #[doc="headers.set("]
    #[doc="    ContentLanguage(vec!["]
    #[doc="        qitem("]
    #[doc="            Language {"]
    #[doc="                primary: \"da\".to_owned(),"]
    #[doc="                sub: None,"]
    #[doc="             }"]
    #[doc="        ),"]
    #[doc="        qitem("]
    #[doc="            Language {"]
    #[doc="                primary: \"en\".to_owned(),"]
    #[doc="                sub: Some(\"gb\".to_owned()),"]
    #[doc="            }"]
    #[doc="        ),"]
    #[doc="    ])"]
    #[doc=");"]
    #[doc="```"]
    (ContentLanguage, "Content-Language") => (QualityItem<Language>)+

    test_content_language {
        test_header!(test1, vec![b"da"]);
        test_header!(test2, vec![b"mi, en"]);
    }
}
